name: Test Stability Report Sync
description: This action syncs automated test results into the QualityForward Automated Test Stability Report.
inputs:
  api-key:
    description: The API key for the project in Quality Forward.
    required: true
  file-path:
    description: The file path that contains the results of automated test executions.
    required: true
  test-framework:
    description: |
      The test framework used.

      Supported Test Frameworks:
      |Test Framework|File Extension|
      |:--:|:--:|
      |junit|xml|
      |pytest|xml|
      |nodejs-playwright|xml|
      |pytest-playwright|xml|
      |magicpod|json|

      ※ For other test frameworks that can output files in junit-xml format, set it to junit.
    required: true
  auto_test_suite_external_key:
    description: |
      The name of the automated test suite to integrate.

      Default automated test suite name if not specified:

      |Test Framework|Default Automated Test Suite Name|
      |:--:|:--|
      |junit,nodejs-playwright|The name attribute of the testsuite element|
      |pytest,pytest-playwright|The classname attribute of the testcase element<br>Taking the part after the last dot.<br>(Example) if test.testSuite, it fetches “testSuite”.|
      |magicpod|Bulk Execution Setting Name for Tests|

  auto_test_cycle_name:
    description: |
      The name of the automated test cycle to integrate.

      Default automated test cycle name if not specified:

      |Test Framework|Default Automated Test Cycle Name|Example|
      |:--:|:--|:--|
      |junit,pytest,nodejs-playwright,pytest-playwright|timestamp attribute of the testsuite element|2024-08-28T15:12:57.311996+09:00|
      |magicpod|End time of bulk test execution|2024-05-09T02:44:32Z|

  auto_execution_device_external_key:
    description: |
      The name of the automated execution device to integrate.

      Default automated test execution environment name if not specified:

      |Test Framework|Default Automated Test Execution Environment Name|
      |:--:|:--|
      |junit,pytest,magicpod|`Standard environment`|
      |nodejs-playwright|hostname attribute of the testsuite element|
      |pytest-playwright|Extracted from the name attribute of the testcase element. <br>(Example) if test_sample[chromium-data-driven], it fetches “chromium”|

runs:
  using: "node20"
  main: "dist/index.js"
